### ISSUE TITLE
[Request] Add some kind of filtering system for global colliders

### ISSUE THREAD

**Issue by Fatalution** [AtiLion/VRCExtended#1]
"Others have local colliders" feature is neat, but it almost always leads to 19 fps and lower. If it's possible, it would be neat to have the ability to turn it off person by person, or at least have a toggle to have it applied globally/only for someone on your friends list.

Thanks for the mod nevertheless!

**Comment by AtiLion** [comment]
Thank you for the request, I will try to add per user local colliders and I am also working on a more optimized version of local colliders that will hopefully improve performance even further

**Comment by Fatalution** [comment]
Take a look at the barebones implementation of GlobalDynamicBones.dll (I used it prior to your mod). I have observed no performance hit (at least no noticeable one) with it.

It only works for you - to other player interaction and back (so no ability to see 3rd party interactions with each other), however, again, feels much faster in terms of performance.

 Installed via 0Harmony.dll and IPA injection

https://dropmefiles.com/RZ4Di

**Comment by AtiLion** [comment]
I looked over the code, it's mostly the same method I use except with that mod it seems to only find the colliders inside the palms.

Meanwhile my mod finds every collider in the avatar. I have a different thought about optimizing the colliders but if you wish I can add an option to only look for the colliders on the hands

**Comment by Fatalution** [comment]
That would make the perfect sense, as the sole purpose of the mod (at least for me) is to be able to touch other avatars - and you do this by hand.

I certainly wish for this to be an option! :) 

Just to clarify, that would mean that I would be able to touch every dynamic bone of any other avatar, but only with my hands, correct? Makes perfect sense as an optimization option to me then. I certainly would look into making this the default for "others have local colliders option" as well, would I be in your place :)

**Comment by AtiLion** [comment]
New version has added this feature as "Target only hand colliders".

Thank you for your suggestion!
