### ISSUE TITLE
[Request]Exclude set Inside DynamicBoneCollider

### ISSUE THREAD

**Issue by ghost** [AtiLion/VRCExtended#2]
Please exclude the collider which is set to inside
If you use an avatar gimmick inside-collider, you will pull another person's Dynamic Bone

sorry I used google translation

**Comment by AtiLion** [comment]
I am not entirely sure what you mean by "excluding the collider which is set to inside".

Do you wish for me to set colliders that are not in your hands to be ignored? If so please refer to issue #1 if not please explain in a bit more details

**Comment by ghost** [comment]
![706b46d77307b57883e4b4fc9726f4bf](https://user-images.githubusercontent.com/45408242/61687575-b747a380-ad5d-11e9-9368-e4231183cf8c.png)
I'm talking about the Dynamic Bone Collider Bound setting
I want to exclude this one because it pulls Dynamic Bone of others when targeted

sorry I used google translation

**Comment by AtiLion** [comment]
Feature has been added to the latest version.

Thank you for the recommendation!
