### ISSUE TITLE
Global dynamic bones are not working with the new VRChat update

### ISSUE THREAD

**Issue by Fatalution** [AtiLion/VRCExtended#3]
Title, the feature just doesn't work now. Any clues?

**Comment by AtiLion** [comment]
Should be working the latest version found in [Releases](https://github.com/AtiLion/VRCExtended/releases/tag/0.4.3)

**Comment by Fatalution** [comment]
Will check it out in an hour and post the results, haven't noticed that the update dropped :)

**Comment by AtiLion** [comment]
Any luck?

**Comment by Fatalution** [comment]
Hello,

Sadly couldn't test yesterday, will test today and report the findings

пт, 2 авг. 2019 г. в 18:20, AtiLion <notifications@github.com>:

**Comment by Fatalution** [comment]
Checked and this is what I found.

Your mod only allows to touch the dynamic bones of the other avatar IF the avatar creator allowed the 3rd party's avatar to be touched by himself as well.

So, if in Unity there is an association between, let's say, hand collider and the dynamic bones in the ear:
1) with VRCextended I can touch the ear of another avatar 
2) I can not touch the ear if there is no association on the avatar I'm trying to touch

The IPA method which I linked in another issue beforehand allows me to touch ANY dynamic bone of another avatar. It doesn't matter if it's set to be "touchable" in Unity.

That's why I thought it doesn't work. I've used IPA method and my friend rarely changes avatars - I was a bit confused when I couldn't touch some of the dynamic bones which were touchable with IPA method to me before.

**Comment by AtiLion** [comment]
The method used in the dll you posted is the exact same as the one that is in VRCExtended, I don't know how you managed to get it to work without the colliders but the dll you provided targets colliders and not bones

**Comment by Fatalution** [comment]
Well, it is how it is. We have tested it by me having the VRCextended and another person having GlobalDynamicBones_IPA dll installed.

The person with the IPA could touch different parts of the avatar which I couldn’t with the VRCExtended. I can provide a video if you would so like

**Comment by AtiLion** [comment]
Okay can you send me the dll that person was using?

**Comment by AtiLion** [comment]
As well as the hooking method

**Comment by Fatalution** [comment]
Its the same IPA global dynamic bones mode that I have already sent in the
issues beforehand :)

ср, 7 авг. 2019 г. в 23:05, AtiLion <notifications@github.com>:

**Comment by AtiLion** [comment]
I no longer have the file or access to the download

**Comment by Fatalution** [comment]
Hello, sorry for the delay.
Here is the dll

https://sharefiles.app/download/3786ab0b336e53634de05f6805cdcd9ff5d0412c

**Comment by AtiLion** [comment]
Hey, thanks for the file. After reviewing the code I have determined that the method of setting the collision between the bone and collider is the same as in VRCExtended, how your friend managed to touch bones without having colliders on his/her hands is most likely done via a different mod that adds the colliders.

As for performance it might be possible it is a bit faster due to a few more checks, however I have determined the the code is very unoptimized, so I am 80% sure that if you use the most optimized settings in VRCExtended you could achieve much better performance than in that mod.

If you have any further questions post them here, close the issue or it will be closed within 48h.

**Comment by Fatalution** [comment]
I have the same mod that my friend has - the IPA file that I have sent.
Dunno why the behavior  is different - but it is :|

сб, 10 авг. 2019 г. в 01:50, AtiLion <notifications@github.com>:

**Comment by Fatalution** [comment]
https://youtu.be/7BTUsu6_gT0

**Comment by Fatalution** [comment]
In regards to the performance, I have found the IPA method to be much more stable and better FPS performance wise.

**Comment by AtiLion** [comment]
I have stopped working on VRCExtended, and have begun working on other mods now. This repo is dead and will be archived.
