### ISSUE TITLE
Interaction with other player's colliders no longer works

### ISSUE THREAD

**Issue by partialimaginations** [AtiLion/VRCExtended#4]
I am no longer able to see other players and myself interact with eachother's colliders after the recent vrchat update

**Comment by partialimaginations** [comment]
woops misclick

**Comment by Groot0075** [comment]
the same thing is happening to me when it comes to interaction with other peoples colliders no longer works after Vrchat updated its self recently.

**Comment by AndyDemon** [comment]
Indeed trying to interact with others no longer works with new VRChat update, I have tried multiple avatars with a friend using the same mod none of our avatars can interact with each other anymore. We can still move our own hair etc but touching each other yields no results.

**Comment by AtiLion** [comment]
The issue is known yes, I am currently recoding the project and it's code progress can be seen on the [fullVersion](https://github.com/AtiLion/VRCExtended/tree/fullVersion) branch

**Comment by ghost** [comment]
I saw you splitting a mod in Discord
Will Dynamic Bone Collider Mod be split?
I need your mod because emmvrc doesn't ignore pull colliders

sorry I used google translation

**Comment by AtiLion** [comment]
Yeah, everything in VRCExtended will now be a separate mod and this repo will be archived

**Comment by AtiLion** [comment]
I have stopped working on VRCExtended, and have begun working on other mods now. This repo is dead and will be archived.
